### ISSUE TITLE
some of the micro app examples not working

### ISSUE THREAD

**Issue by pranav-singhal** [objecthub-io/ObjectHub#259]
I came across two example micro apps that you had uploaded as examples and they were not working. The images below show what I was getting in the preview screen. Also they are not present in the repository.
the micro apps are

- Today

- Apps.embed() example

I forked them from the documentation and uploaded them myself.
You can link your docs to these micro apps instead. (they are the same name as yours)
<img width="1280" alt="screen shot 2017-07-01 at 7 10 23 pm" src="https://user-images.githubusercontent.com/29460541/27762542-8fd3349e-5e91-11e7-8260-1a532f164254.png">
<img width="1280" alt="screen shot 2017-07-01 at 7 10 32 pm" src="https://user-images.githubusercontent.com/29460541/27762543-8fd42174-5e91-11e7-9e60-a8792af68f31.png">

**Comment by pranav-singhal** [comment]
Here's another one!
<img width="1279" alt="screen shot 2017-07-01 at 7 27 12 pm" src="https://user-images.githubusercontent.com/29460541/27762615-622fa6c4-5e93-11e7-8b75-ffdf67999cd6.png">

**Comment by objecthub-io** [comment]
Thank you for reporting this issue and for releasing the forked Micro Apps. 

This issue should be fixed now. Note that for updates in the documentation to occur, it might be necessary to clear the browsers local storage (`localStorage.clear()`) .

**Comment by pranav-singhal** [comment]
I just checked, the issue is still there. the micro app called "Apps.embed() Example" is still showing the same error. I think you need to redirect this link to the version of the app that I released.
<img width="1280" alt="apps_embed" src="https://user-images.githubusercontent.com/29460541/27767316-7a99bf00-5f11-11e7-9f8f-2ba8e4fefa22.png">

**Comment by objecthub-io** [comment]
This should be fixed now.

If still the wrong object shows up in the repository, try loading the documentation in a Chrome Incognito tab and/or clear the browsers localStorage.

**Comment by objecthub-io** [comment]
Closing fixed issue.
